### ISSUE TITLE
Fails on Arch Linux

### ISSUE THREAD

**Issue by TheMarex** [mapbox/mason#102]
This fails on Arch Linux as it does not provide a release file.

https://github.com/mapbox/mason/blob/master/mason.sh#L77

It should not generate a hard failure but deal with an empty distribution string.

/cc @springmeyer

**Comment by TheMarex** [comment]
Should be addressed by https://github.com/mapbox/mason/pull/103

**Comment by springmeyer** [comment]
> It should not generate a hard failure but deal with an empty distribution string.

Sounds good. Thanks for testing and getting things working on arch! I'll followup #103 by adding a unit test for accepting an unknown distribution (will be nice also for testing linux installs/packaging via os x, aka "cross-installs").

**Comment by springmeyer** [comment]
#103 is merged. Keeping open till I have a chance to add tests per comment above.

**Comment by springmeyer** [comment]
closing. no need for tests since that code was unused and obsolete - removed in 4c71c86
