### ISSUE TITLE
Create branch for geowave-jace-0.8.7

### ISSUE THREAD

**Issue by jwomeara** [mapbox/mason#105]
This would be in support of the [geowave-plugin](https://github.com/mapnik/geowave-plugin) for mapnik.

An implementation can be found in my mason fork [here](https://github.com/jwomeara/mason/tree/geowave-jace-0.8.7).  I can submit the pull request once the branch is created.

**Comment by kkaefer** [comment]
Done in https://github.com/mapbox/mason/commit/930199dc87cdac81a7f22f2019ac3828a37380f4.

**Comment by jwomeara** [comment]
Woohoo!  Thanks!
