### ISSUE TITLE
Support .tbd as MASON_DYNLIB_SUFFIX on Xcode7 builds

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mason#113]
`mason install libcurl-system` is currently failing for me with the following error:
```
* Loading install script 'https://github.com/mapbox/mason/blob/libcurl-system/script.sh'...
Can't find library file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib/libcurl.dylib
```
After upgrading to Xcode7, ``libcurl.dylib` doesn't exist in that path anymore, but `libcurl.tbh` lives there instead.

**Comment by 1ec5** [comment]
@kkaefer, you were looking at this previously, correct? Is it sufficient to just link against the .tbd file instead of the .dylib?

**Comment by kkaefer** [comment]
I don't remember.
