### ISSUE TITLE
Support OS X 10.11 (aka El Cap)

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#118]
Currently travis only builds binaries for OS X 10.10. So anyone upgrading to El Cap will immediately be hit with having to build from source.

Two potential solutions:

1) Start building for both 10.10 and 10.11 on travis

2) Stop versioning on `${MASON_PLATFORM_VERSION}`. In other words stop having binaries use `10.10` in the path such that binaries built on `10.10` will still be found (and will work) on 10.11 (refs https://github.com/mapbox/mason/issues/38#issuecomment-145685563_

2) is vastly better and simple, we just need to think through a way to move on it in a back compatible way.

/cc @mikemorris @1ec5 @incanus @kkaefer

**Comment by mikemorris** [comment]
I've been building 10.11 binaries with [`osx_image: xcode7`](https://github.com/mapbox/mason/blob/geojsonvt-2.1.6/.travis.yml#L6)

**Comment by kkaefer** [comment]
We should do 2). Before El Capitan was released, I manually copied over all binaries from osx-10.10 to osx-10.11, but that is only a stopgap solution.

**Comment by jfirebaugh** [comment]
We need to do this -- the current situation is that the `osx-10.11` copies @kkaefer made don't get updated and don't get new package versions, leading to much confusion.
