### ISSUE TITLE
'make linux' requires specific clang versions on Ubuntu 14.04

### ISSUE THREAD

**Issue by desert** [mapbox/mason#123]
In order to build on Ubuntu 14.04 you need different version of Clang and its alias.

  # apt-get install clang++-3.6
  #  ln -s /usr/bin/clang++-3.6 /usr/bin/clang
  #  install a gcc-4.9 from your favorite ppa

This is important because 14.04 is a LTS release and will be around us for some more years to come.

This is a documentation bug IMHO

**Comment by jfirebaugh** [comment]
Which mason package are you referring to?
