### ISSUE TITLE
Put all package scripts in one branch; use Travis "triggered builds" API

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mason#132]
Currently, we use the branch name to communicate to Travis the package name and version to build. This imposes significant branch management overhead, particularly when making changes to mason that require the modification of several packages.

Travis has a [triggered build API](https://docs.travis-ci.com/user/triggering-builds) in beta which allows triggering a build with arbitrary commit message, build configuration, and environment variables. There ought to be a way we can use one of those channels to communicate the package name and version, allowing us to store all the package scripts in a single branch.

**Comment by springmeyer** [comment]
> allowing us to store all the package scripts in a single branch.

This would be a major efficiency win, so I'm :+1: to thinking about easy ways to make this viable.

**Comment by jfirebaugh** [comment]
Done in #133.
