### ISSUE TITLE
Eliminate MASON_DIR

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mason#140]
Instead of requiring a `MASON_DIR` environment variable, mason should locate everything using paths relative to the location of the `mason` script.

**Comment by springmeyer** [comment]
Now that scripts are in the same directory tree as mason itself, this should be possible :+1: Will require quite a bit of script cleanup, but we could team up on that.

**Comment by jfirebaugh** [comment]
`MASON_DIR` is handled internally as of #141.
