### ISSUE TITLE
Postgis 2.2.2 package: missing geos symbols

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#150]
The mac 2.2.2 package is working, but the linux one is broken such that postgis raster will not load:

```
ERROR:  could not load library "/home/travis/build/springmeyer/postgis-mason-install/mason_packages/linux-x86_64/postgis/2.2.2/lib/rtpostgis-2.2.so": /home/travis/build/springmeyer/postgis-mason-install/mason_packages/linux-x86_64/postgis/2.2.2/lib/rtpostgis-2.2.so: undefined symbol: _ZTIN4geos4geom10LinearRingE
```

This is likely a linking order issue that will be easy to fix once I have a chance to debug locally on linux.

/cc @ingalls

**Comment by springmeyer** [comment]
@ingalls - all clear: linux binary is now working for `postgis v2.2.2` package.

**Comment by ingalls** [comment]
Woah this is fantastic!! I'll start playing around with this early next week!
