### ISSUE TITLE
installation fail

### ISSUE THREAD

**Issue by filipc** [mapbox/mason#154]
I'm trying to install mason on Mac following the steps from readme.
 
```
git clone -b master --single-branch https://github.com/mapbox/mason.git ~/.mason
Cloning into '/Users/Filip/.mason'...
remote: Counting objects: 4985, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4985 (delta 5), reused 3 (delta 3), pack-reused 4978
Receiving objects: 100% (4985/4985), 1.53 MiB | 633.00 KiB/s, done.
Resolving deltas: 100% (1315/1315), done.
Checking connectivity... done.
```

and then: 

`sudo ln -s ~/.mason/mason /usr/local/bin/mason`
 
when I'm trying to run mason it seems that it is working fine:

```
mason
Usage: /usr/local/bin/mason <command> <lib> <version>
```
 
but it's not. When trying to use any command I've got error:

```
mason env PATH
/usr/local/bin/mason: line 27: /usr/local/bin/mason.sh: No such file or directory 
```

File mason.sh is in .mason in User home directory, not in /usr/local/bin. I'm little confused.

**Comment by springmeyer** [comment]
I think you also need to do `export MASON_DIR=${HOME}/.mason/` until #140 is fixed.

**Comment by filipc** [comment]
It works now. Thanks.
