### ISSUE TITLE
missing ios 9.2 binaries for geojson-vt-cpp 4.1.2

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mason#156]
Somehow cbe97886ec604018ea8b0faf1cf28658125e162d missed ios-9.2 binaries. In mapbox-gl-native I see:

```
* Binary not available yet for ios-9.2/geojsonvt/4.1.2.tar.gz
* Downloading https://github.com/mapbox/geojson-vt-cpp/archive/v4.1.2.tar.gz...
```

followed by building from source.

cc @brunoabinader

**Comment by tmpsantos** [comment]
Just a heads-up that the binaries are missing for Linux on purpose.
https://github.com/mapbox/mason/issues/155

**Comment by jfirebaugh** [comment]
@brunoabinader Did you run `mason trigger geojson-vt-cpp 4.1.2`? I don't see a triggered build for this version in the [build history](https://travis-ci.org/mapbox/mason/builds).

**Comment by jfirebaugh** [comment]
@tmpsantos I don't think selectively avoiding precompiled binaries is a sustainable practice. If we really need libstdc++ >= 5.1 support right now, we should build that as a custom version suffix (see #157).

**Comment by brunoabinader** [comment]
@jfirebaugh thanks for the reminder, it is done now: https://travis-ci.org/mapbox/mason/builds/124175084

**Comment by tmpsantos** [comment]
Oh, the Linux binaries got re-uploaded and it cxx11 ABI is broken again :cry:

**Comment by jfirebaugh** [comment]
@tmpsantos I suggest you either:

* Create `4.1.2-cxx11` and use the latter where you need the cxx11 ABI, or
* Create `4.1.2-cxx03`, update mapbox-gl-js to use it, and then change `4.1.2` to be built with cxx11 ABI
