### ISSUE TITLE
restore gtest binaries

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mason#160]
Linux gtest binaries were removed from S3 -- https://github.com/mapbox/mason/issues/155#issuecomment-211422329.

Compiling gtest from source rather than using prebuilt binaries increases the build time. Looks like for mapbox-gl-native it adds a minute or two.

@tmpsantos, can you please restore the prebuilt binaries and investigate approaches in #157 for `cxx11abi`?

**Comment by tmpsantos** [comment]
Done, I tested it on the bots and everything is back to normal.

Apologies for the inconvenience and I will do something on the lines of `cxx11abi`.
