### ISSUE TITLE
Provide mason linux-x86_64 binaries for clang-tidy 3.8

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mason#188]

**Comment by springmeyer** [comment]
clang-tidy is available as part of the `clang` v3.8.0 package. I've been thinking that if there is a need for just sub-parts of that fairly large package, then we could re-create, for example, the `clang-tidy` package to just pull from the clang v3.8.0 binaries and repackage just the clang-tidy tool. It should be statically linked and so will work standalone.

**Comment by brunoabinader** [comment]
@springmeyer it seems `clang-format` comes from the same repository as `clang-tidy` - it could be useful to have a binary package of it for e.g. https://github.com/mapbox/mapbox-gl-native/issues/5342.

**Comment by springmeyer** [comment]
@brunoabinader - sure, sounds good. Should be easy to do a `clang-format` package similar to https://github.com/mapbox/mason/pull/189/files. Want to ticket that?

**Comment by brunoabinader** [comment]
> Want to ticket that?

👉 #190 

Super awesome! Thanks @springmeyer 😄

**Comment by brunoabinader** [comment]
Fixed in https://github.com/mapbox/mason/pull/189.
