### ISSUE TITLE
Triggered builds are forced to download clang

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mason#203]
The improvements in #185 had the side-effect of forcing triggered builds to download clang 3.8, and produce additional builds: https://travis-ci.org/mapbox/mason/builds/141579167

There should be only two builds, but Travis is running 4 builds, two of which are going to fail.

/cc @springmeyer

**Comment by springmeyer** [comment]
I think the problem is this syntax:

```
sudo: false
 
 os:
   - linux
   - osx
```

interacts in undesirable ways with the `matrix`. So the solution is to update the `.travis.yml` for the given package to only use `sudo` and `os` within a `matrix`. Does that sound right @kkaefer?

**Comment by springmeyer** [comment]
Closing,

```
    - os: linux
      sudo: false
```

Is the only known workaround for this travis oddity and works once applied.
