### ISSUE TITLE
OpenSSL versions

### ISSUE THREAD

**Issue by camilleanne** [mapbox/mason#217]
None of the openssl versions in the scripts directory are not available for download anymore at ftp://ftp.openssl.org/source/. They should be updated to the most recent or removed.

**Comment by springmeyer** [comment]
Agree. Probably should remove them. I can do this after checking/confirming that mapbox-gl-native no longer needs or uses them. Did you notice because you need ssl support? /cc @tmpsantos just package libcrypto which might be useful.

**Comment by tmpsantos** [comment]
> Did you notice because you need ssl support

`libcurl` depends on them and we use `libcurl` on Mapbox GL Native. Made a PR on #218 that fixes the URLs.

**Comment by camilleanne** [comment]
@springmeyer I needed md5 for something and didn't really know where else to find it, so I was digging around. I no longer need openssl, though.

**Comment by springmeyer** [comment]
closing per fix at #218
