### ISSUE TITLE
gtest 1.7.0 source URL has been moved

### ISSUE THREAD

**Issue by eek001c** [mapbox/mason#265]
Getting 404 error for https://googletest.googlecode.com/files/gtest-1.7.0.zip

**Comment by eek001c** [comment]
Same thing for gtest 1.7.0-cxx11abi

**Comment by jfirebaugh** [comment]
https://github.com/google/googletest/issues/901

For now I'm going to copy over existing binaries over for ios-10.0.

**Comment by kkaefer** [comment]
fixed in #272

**Comment by eek001c** [comment]
gtest 1.7.0-cxx11abi still pointing to old url
