### ISSUE TITLE
/usr/local/bin/mason: line 54: /usr/local/bin/mason.sh: No such file or directory

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mason#27]
Installed like
```
git clone https://github.com/mapbox/mason.git ~/.mason
sudo ln -s ~/.mason/mason /usr/local/bin/mason
```
then hit this error trying to `mason install libpng 1.6.13` on a Ubuntu 14.04 VM
```
/usr/local/bin/mason: line 54: /usr/local/bin/mason.sh: No such file or directory
```
Running the follow from home directory works fine however.
```
./.mason/mason build libpng 1.6.13
```

**Comment by springmeyer** [comment]
not sure about this one. If it is still present let's track/discuss at https://github.com/mapbox/mason/issues/69
