### ISSUE TITLE
openssl linking broken on OSX

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#28]
Seeing:

```
Undefined symbols for architecture x86_64:
  "_OPENSSL_ia32cap_P", referenced from:
      _sha1_block_data_order in libcrypto.a(sha1-x86_64.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [link_app.] Error 1
make[1]: *** [rc4test] Error 2
```

**Comment by mikemorris** [comment]
Seeing this too, this is now blocking switching `mapbox-gl-native` off of system libraries for publishing binaries.

**Comment by springmeyer** [comment]
Yeah, I've never been able to solve this, hopefully we can leapfrog by using boringssl instead /cc @ljbade

**Comment by ljbade** [comment]
Hmm, it looks like it is using the 32bit assembly instead of the 64-bit. Have you checked which assembly files in is compiling?
