### ISSUE TITLE
Curl usage in mason.cmake may error unexpectadly

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#289]
Seeing this in a docker container with ubuntu precise. 

This works:

```
/usr/bin/curl  https://mason-binaries.s3.amazonaws.com/linux-x86_64/boost_libthread/1.61.0.tar.gz -o out
```

This (using all the flags used inside mason.cmake) does not work:

```
/usr/bin/curl --retry 3 -s -f -S -L  https://mason-binaries.s3.amazonaws.com/linux-x86_64/boost_libthread/1.61.0.tar.gz -o out
curl: (6) Couldn't resolve host 'mason-binaries.s3.amazonaws.com'
````

I think @daniel-j-h has hit this before as well.

/cc @kkaefer

**Comment by springmeyer** [comment]
Oddly it appears that each failed request succeeds on the second attempt.

**Comment by kkaefer** [comment]
This seems really weird... I just checked all of the flags and it doesn't appear that any of them would invoke a behavior that affects DNS resolution `-L` makes curl follow redirects, but there shouldn't be any redirects on the way to download the file.

I just set up a test docker container and manually reran both commands. I can replicate the error message with the second command in many cases, however, I also get the same error when running the first command. Frequently, I see the first invocation succeed, but subsequent invocations fail.

**Comment by daniel-j-h** [comment]
> I think @daniel-j-h has hit this before as well.

No - what I experienced with the mason integration in osrm-backend was mason's curl invocation not respecting the env var `SSL_CERT_FILE` pointing to the cert file from the `ca-certificates` package.

Basically this: https://github.com/NixOS/nix/issues/921

**Comment by kkaefer** [comment]
I did some further debugging with `strace` and `tcpdump`. What appears to be happening is that cURL uses a nameserver run by the docker daemon:

```
$ cat /etc/resolv.conf`
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
nameserver 192.168.65.1
# /etc/resolv.conf.tail can replace this line
```

A successful response from that DNS server looks like this:

```
09:44:18.168039 IP (tos 0x0, ttl 64, id 62752, offset 0, flags [DF], proto UDP (17), length 77)
    172.17.0.9.44229 > 192.168.65.1.53: [bad udp cksum 0xae0e -> 0x5c36!] 47489+ AAAA? mason-binaries.s3.amazonaws.com. (49)
09:44:18.168416 IP (tos 0x0, ttl 37, id 48844, offset 0, flags [none], proto UDP (17), length 98)
    192.168.65.1.53 > 172.17.0.9.44229: [udp sum ok] 47489- q: AAAA? mason-binaries.s3.amazonaws.com. 1/0/0 mason-binaries.s3.amazonaws.com. [39m59s] CNAME s3-1-w.amazonaws.com. (70)
09:44:18.168644 IP (tos 0x0, ttl 64, id 62753, offset 0, flags [DF], proto UDP (17), length 77)
    172.17.0.9.39033 > 192.168.65.1.53: [bad udp cksum 0xae0e -> 0x728b!] 53880+ A? mason-binaries.s3.amazonaws.com. (49)
09:44:18.287580 IP (tos 0x0, ttl 37, id 1528, offset 0, flags [none], proto UDP (17), length 114)
    192.168.65.1.53 > 172.17.0.9.39033: [udp sum ok] 53880
    q: A? mason-binaries.s3.amazonaws.com.
    2/0/0 mason-binaries.s3.amazonaws.com.
    [39m59s] CNAME s3-1-w.amazonaws.com., s3-1-w.amazonaws.com.
    [4s] A 54.231.121.43 (86)
```

An unsuccessful response looks like this:
```
09:43:36.938513 IP (tos 0x0, ttl 64, id 59990, offset 0, flags [DF], proto UDP (17), length 77)
    172.17.0.9.34774 > 192.168.65.1.53: [bad udp cksum 0xae0e -> 0xf5bc!] 17642+ AAAA? mason-binaries.s3.amazonaws.com. (49)
09:43:36.939111 IP (tos 0x0, ttl 37, id 44576, offset 0, flags [none], proto UDP (17), length 98)
    192.168.65.1.53 > 172.17.0.9.34774: [udp sum ok] 17642- q: AAAA? mason-binaries.s3.amazonaws.com. 1/0/0 mason-binaries.s3.amazonaws.com. [39m59s] CNAME s3-1-w.amazonaws.com. (70)
09:43:36.939508 IP (tos 0x0, ttl 64, id 59991, offset 0, flags [DF], proto UDP (17), length 77)
    172.17.0.9.47164 > 192.168.65.1.53: [bad udp cksum 0xae0e -> 0x551a!] 53286+ A? mason-binaries.s3.amazonaws.com. (49)
09:43:36.942823 IP (tos 0x0, ttl 37, id 40661, offset 0, flags [none], proto UDP (17), length 114)
    192.168.65.1.53 > 172.17.0.9.47164: [udp sum ok] 53286- 
    q: A? mason-binaries.s3.amazonaws.com.
    2/0/0 s3-1-w.amazonaws.com.
    [4s] A 54.231.120.235, mason-binaries.s3.amazonaws.com.
    [40m] CNAME s3-1-w.amazonaws.com. (86)
curl: (6) Couldn't resolve host 'mason-binaries.s3.amazonaws.com'
```

It seems like when querying for `mason-binaries.s3.amazonaws.com`, the unsuccessful response is for `s3-1-w.amazonaws.com`, while successful responses return an answer for `mason-binaries.s3.amazonaws.com` which was queried. I was able to replicate this behavior with `dig:

**Correct response**
```
;; ANSWER SECTION:
mason-binaries.s3.amazonaws.com. 1668 IN CNAME	s3-1-w.amazonaws.com.
s3-1-w.amazonaws.com.	4	IN	A	54.231.81.250
```

**Incorrect response**
```
;; ANSWER SECTION:
s3-1-w.amazonaws.com.	4	IN	A	54.231.81.250
mason-binaries.s3.amazonaws.com. 1668 IN CNAME	s3-1-w.amazonaws.com.
```

What appears to be happening is that the order of the responses is just switched around, and `getaddrinfo` in Ubuntu 12.04 seems to choke on that. I've found conflicting information on whether this is a bug in Docker's DNS server or a bug in `getaddrinfo`. RFC 1034 says in [section 4.3.1](https://tools.ietf.org/html/rfc1034#section-4.3.1) that the answer should be ("prefaced by one or more CNAME RRs [Resource Records] that specify aliases encountered on the way to an answer."*, but in [section 3.6](https://tools.ietf.org/html/rfc1034#section-3.6) it says that *"The order of RRs in a set is not significant, and need not be preserved by name servers, resolvers, or other parts of the DNS."*. I'm getting the same misordered(?) responses in Ubuntu 14.04, but its implementation of `getaddrinfo` seems to be able to resolve the name correctly, even if the `A` record appears first.

A solution that works for Ubuntu 12.04 is to start docker with `--dns 8.8.8.8`, or some other DNS server (like BIND)B that is known to return records in `CNAME`, then `A` order.

**Comment by springmeyer** [comment]
Thank you so much for investigating @kkaefer  and great to know the workaround. I'll close this now that it is clear it is a docker problem rather than a mason problem.

**Comment by kkaefer** [comment]
It's not a Docker problem; Docker is behaving correctly (but unusual). The issues is in the `getaddrinfo` implementation that ships with Ubuntu 12.04, which fails to interpret the unusual response. Newer Ubuntu versions work fine.
