### ISSUE TITLE
Remove luabind package

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#306]
Luabind is packaged only for OSRM. OSRM dropped the dep in https://github.com/Project-OSRM/osrm-backend/commit/0f59b78c02f46b4fca71dbe6ce6f95ae7a94b0f9 🎉 . /cc @daniel-j-h @karenzshea

**Comment by daniel-j-h** [comment]
Note: LuaJIT is also gone from OSRM by now.

- https://github.com/Project-OSRM/osrm-backend/issues/2955
- https://github.com/mapbox/mason/tree/master/scripts/luajit

**Comment by springmeyer** [comment]
Done in a56fbba
