### ISSUE TITLE
Update LLVM-based packages to latest stable LLVM 3.9.1 release

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mason#308]
This effects all LLVM-based packages such as clang++, clang-format, llvm, etc.

(Sidenote: why is there a clang++ _and_ a (outdated?) clang mason package?)

**Comment by springmeyer** [comment]
Will keep open until I've built binaries for linux (a manual process).

**Comment by springmeyer** [comment]
Packages built and uploaded for OS X. Currently hitting this problem on linux:

```
-- Symbols (liblldb): only exporting liblldb.exports symbols
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CURSES_CURSES_LIBRARY (ADVANCED)
    linked by target "include-what-you-use" in directory /home/ubuntu/mason/mason_packages/.build/llvm-3.9.1/tools/clang/tools/include-what-you-use

-- Configuring incomplete, errors occurred!
```

**Comment by springmeyer** [comment]
Solved with `sudo apt-get install libncurses5-dev` for now, followup will be to package libcurses to enable statically linking include-what-you-use against it (https://github.com/mapbox/mason/issues/309)

**Comment by springmeyer** [comment]
Done, linux packages are up and confirmed they work with variant (as a starting test): https://github.com/mapbox/variant/pull/135
