### ISSUE TITLE
version valgrind package

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mason#318]
The valgrind package currently has only a ["latest" version](https://github.com/mapbox/mason/tree/master/scripts/valgrind/latest). This is misleading, as installing this package will give you the binary that was precompiled at a specific point in time, not the latest from the repository. (And we don't want dependencies to "float" like that anyway.)

We should switch to a versioned release, or at least a specific commit hash.

@brunoabinader, do you recall why we needed to use pre-release code at the time?

**Comment by jfirebaugh** [comment]
Added a 3.12.0 package in 639affb2b78cfebf12b437df0ada9c5197424891.

**Comment by brunoabinader** [comment]
@jfirebaugh yes - IIRC it was due to a segfault in previous stable versions of valgrind preventing it from running as part of the Qt5 build bot on Travis.
