### ISSUE TITLE
Dependency on other mason packages?

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mason#32]
llvm-3.5 from the Ubuntu PPA [isn't even close](https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-3.5/+bug/1372062) to llvm 3.5.0 built from source from http://llvm.org/releases/download.html#3.5

Is there a way to make the mason package for mesa-10.3.3 depend on a mason package for llvm-3.5?

**Comment by springmeyer** [comment]
Closing. The current convention in mason is to hook into the `mason_prepare_compile` for build deps. There is no current support for runtime deps knowledge.
