### ISSUE TITLE
v0.4.0 tag broke your mapnik build

### ISSUE THREAD

**Issue by tjwebb** [mapbox/mason#325]
The node-mapnik Travis-CI build script relies on this project to install clang, but the clang folder was removed from https://github.com/mapbox/mason/tree/v0.4.0/scripts between 0.3.0 and 0.4.0.

**Comment by springmeyer** [comment]
The compiler removal was intentional. The mistake of mine is to ever have had node-mapnik depending on unpinned mason. This is fixed in https://github.com/mapnik/node-mapnik/commit/888474b3cad088561e5a68dc05518ec312e8c25c.
