### ISSUE TITLE
Should mason install deps?

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mason#33]
Currently mason doesn't install dependencies for [mesa-10.3.1](https://github.com/mapbox/mason/tree/mesa-10.3.1), only installing them [on Travis](https://github.com/mapbox/mason/blob/mesa-10.3.1/.travis.yml#L19-L20). Should dependencies be checked/installed when a mason package is installed?

**Comment by springmeyer** [comment]
Stale. Mason does not currently have support for installing runtime deps. The latest mesa package attempts to statically link as much as possible therefore: https://github.com/mapbox/mason/pull/324
