### ISSUE TITLE
Document development environment?

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mason#34]
@kkaefer @springmeyer How do your have a development environment set up for working locally and testing build scripts before pushing? Since mason always pulls from remote branches, I'm finding myself frequently pushing to "live" branches just to test code, which feels wrong. I'd like be able to easily work on build scripts locally, and maybe establish some sort of convention around `-dev` or similar branch names for remote testing.

**Comment by springmeyer** [comment]
Closing as stale. Latest readme has updated instructions on installing and use: https://github.com/mapbox/mason#installation
