### ISSUE TITLE
Build Static Intel TBB Library

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mason#341]
At the moment Mason builds a shared library for Intel TBB. This is the [recommended way](https://www.threadingbuildingblocks.org/faq/11) of using Intel TBB: its task scheduler needs full control of the environment.

At the same time it's unfortunate and there are use-cases where we want to statically link in Intel TBB. For these use-cases we should also provide a statically linked Intel TBB library:

    make extra_inc=big_iron.inc

See: https://github.com/01org/tbb/blob/tbb_2017/build/big_iron.inc#L19-L76

Here is a use-case where a statically linked Intel TBB library is not a good idea: statically linking Intel TBB for `libosrm` and then users linking in a second Intel TBB library (think: users calling libosrm's Route function in parallel with Intel TBB). This will most likely work but oversubscribe the machine.

Where it makes sense: free standing binaries, such as `osrm-extract` and related. Also node bindings.

cc @danpat 

Retaed: update to latest stable Intel TBB first https://github.com/mapbox/mason/issues/340

**Comment by springmeyer** [comment]
Working on this in #343

**Comment by daniel-j-h** [comment]
This landed with https://github.com/mapbox/mason/pull/343. The mason tbb 2017_20161128 package now comes with a static library, too. :sparkles:

cc @danpat
