### ISSUE TITLE
getting platform params on arch linux fails

### ISSUE THREAD

**Issue by preet** [mapbox/mason#36]
By default lsb-release isn't installed on Arch, so trying to get release info that way fails right off the bat. After manually installing it, arch creates two files in /etc/:

```
[preet@s etc]$ cat arch-release
Arch Linux release

[preet@s etc]$ cat lsb-release
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
```

Mason fails when it tries to read in arch-release. Maybe detect if the string "LSB_VERSION" is in the file before trying to read in the release info? Or just specify the full name 'lsb-release' (are there distros where its named differently?)

**Comment by stalkerg** [comment]
Gentoo too:
cat gentoo-release
Gentoo Base System release 2.2

I fix path to /etc/lsb-release and was manual add DISTRIB_RELEASE version.

**Comment by springmeyer** [comment]
The maintainers of mason generally test and build packages on ubuntu only. We are happy to review PRs for other systems if they include test that can run on travis that mock those systems to ensure the support works as expected and stays working.
