### ISSUE TITLE
OS X improvements

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#38]
My opinion is:

1) Mason package versioning on OS X should not use `${MASON_PLATFORM_VERSION}` when versioning binaries for OSX. So instead of `./mason_packages/osx-${MASON_PLATFORM_VERSION}` or `./mason_packages/osx-10.10` packages should be stored in: `./mason_packages/osx-${ARCH}`. We should then enforce a minimum OS X version Mason will build for and stick to it. I propose `10.8` and we'd then enforce all packages are built with `-mmacosx-version-min=10.8`.

2) We should not support 32 bit OS X since it is such a rare platform these days. I propose:

```diff
diff --git a/mason.sh b/mason.sh
index 78d76ba..385b587 100644
--- a/mason.sh
+++ b/mason.sh
@@ -37,7 +37,7 @@ if [ ${MASON_PLATFORM} = 'osx' ]; then
 
     MASON_SDK_ROOT=${MASON_XCODE_ROOT}/Platforms/MacOSX.platform/Developer
     MASON_SDK_PATH="${MASON_SDK_ROOT}/SDKs/MacOSX${MASON_PLATFORM_VERSION}.sdk"
-    export MASON_CFLAGS="-mmacosx-version-min=${MASON_PLATFORM_VERSION} -isysroot ${MASON_SDK_PATH} -arch i386 -arch x86_64"
+    export MASON_CFLAGS="-mmacosx-version-min=${MASON_PLATFORM_VERSION} -isysroot ${MASON_SDK_PATH} -arch x86_64"
 
```

**Comment by ljbade** [comment]
Adding note that this also applies to Ubuntu (or any Linux?)

**Comment by springmeyer** [comment]
About to move on fixing this. Before I do I'll note that the current usage of 

 > export MASON_CFLAGS="-mmacosx-version-min=${MASON_PLATFORM_VERSION} -isysroot ${MASON_SDK_PATH} -arch i386 -arch x86_64"

Is broken/not doing anything because `MASON_CFLAGS` are not respected anywhere. I'm going to move to just setting `CFLAGS` and `CXXFLAGS` like #48 for now. We can revisit and use MASON prefixed name later on if avoiding clashes with parent env becomes an issue.

**Comment by kkaefer** [comment]
Agreed, `macosx-x86_64` seems a lot saner.

**Comment by springmeyer** [comment]
This is mostly done in https://github.com/mapbox/mason/commit/d43175d51fa4df4a2995ceac7cff7a6560ad01e8, but one big thing remains. Now that our binaries support 10.8 and greater we no longer need to version on the `${MASON_PLATFORM_VERSION}`.

The question is how to introduce this change without breaking the world...

**Comment by jfirebaugh** [comment]
⇢ #118 / #131
