### ISSUE TITLE
llvm 4.0.0 package

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#385]
The official llvm 4.0.0 release is out, so next steps are to:

 - [x] pin the existing llvm 4.0.0 mason package to the release tarballs (currently pointed to git head)
 - [x] rebuild and republish 4.0.0
 - [ ] create a 5.0.0 package that points at upstream llvm to begin allowing that to be tested

I'm out today, but will plan to hit this tomorrow.

/cc @kkaefer @daniel-j-h

**Comment by kkaefer** [comment]
> create a 5.0.0 package that points at upstream llvm
Can we please name it `5.0.0-pre-<gitsha>`? or something like that?

**Comment by springmeyer** [comment]
> Can we please name it 5.0.0-pre-<gitsha>? or something like that?

👍 @kkaefer

**Comment by springmeyer** [comment]
Per #386 llvm 4.0.0 packages are now available. Not yet found the time to build 5.0.0-pre packages.

**Comment by springmeyer** [comment]
> create a 5.0.0 package that points at upstream llvm to begin allowing that to be tested

Closing, not going to move on this now. Will reconsider if there is a specific need.
