### ISSUE TITLE
System libz tries to use Linux headers instead of Android's

### ISSUE THREAD

**Issue by ljbade** [mapbox/mason#42]
Just noticed that on a system without libz-dev installed, the Android install of libz-system fails when it goes to compile the verison check utility. It can't be using the header from the Android NDK.

**Comment by ljbade** [comment]
@springmeyer  Should we just switch Android to binary libz as part of system-lib purge?

**Comment by springmeyer** [comment]
> the verison check utility

This utility I've found is quite brittle/non-starter when cross-compiling. I think we should consider alternatives, but I've not looked closely yet at what depends on it.

> springmeyer Should we just switch Android to binary libz as part of system-lib purge?

libz is the one library I've found to be viable to use dynamically and still be portable. I presume Android provides it? If so what would it take to reliably use the Android zlib without conflicting others on the host machine?

**Comment by ljbade** [comment]
@springmeyer it should be possible to set sysroot and tell compiler to not search default locations?

**Comment by ljbade** [comment]
I will move to non-system libz

**Comment by springmeyer** [comment]
>  it should be possible to set sysroot and tell compiler to not search default locations?

Yes, but that is brittle. In my experience it is far more predictable to only put on the compiler/linker paths custom directories you want to link to as discussed in #65 and achieved by using symlinks to system files into a custom directory. You can also set `C_INCLUDE_PATH`, `CPLUS_INCLUDE_PATH`, and `LIBRARY_PATH` to that custom directory to help the compiler prefer them over system directories. Let's hope this gets solved eventually by c++17: http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2014/n4214.pdf
