### ISSUE TITLE
Minjur dependency not found (Not sure where the fix needs to be)

### ISSUE THREAD

**Issue by arunasank** [mapbox/mason#423]
I am having some trouble with using mason in my install scripts. When I install minjur and try to run it, I get this error:

```
minjur: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by minjur)
minjur: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by minjur)
```

I have a feeling this is introduced from using the mason package for it because:
1. I didn't see this error when I built minjur from source
2. I have `libstdc++6` installed in my Dockerfile

I was looking at https://github.com/mapbox/mason/blob/master/scripts/minjur/0.1.0/script.sh
and wasn't sure of what to do next.

cc/ @springmeyer

**Comment by springmeyer** [comment]
Per chat, the solution is to add the ubuntu-toolchain PPA before installing `libstdc++` as per https://github.com/mapbox/cpp#using-apt-get-directly
