### ISSUE TITLE
Package LLVM 4.0.1 bugfix release

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mason#438]
- http://lists.llvm.org/pipermail/llvm-announce/2017-July/000074.html
- http://releases.llvm.org/download.html

**Comment by springmeyer** [comment]
👍  I will take this on.

**Comment by springmeyer** [comment]
Packages are published and new docs on the process to create them are ready for review at https://github.com/mapbox/mason/pull/452. Will close this now and track at #452
