### ISSUE TITLE
MASON_DIR refers to master only

### ISSUE THREAD

**Issue by ljbade** [mapbox/mason#44]
I have a need to refer to files in the branch that holds the `script.sh` file. On Travis this maps to `~/build/mapbox/mason` but likely different in other contexts.

There is the variable `MASON_DIR` which maps to `~/mason.sh` which is where mason master branch is checked out.

There is no way to get the `script.sh` branch as far as I can see.

/cc @springmeyer

**Comment by springmeyer** [comment]
/cc @kkaefer for ideas. My understanding is that this is by design.

> I have a need to refer to files in the branch that holds the script.sh file

I've also been keen to do this: to be able to keep patch files beside the ./script.sh but I'm not aware of a good way to do it yet.

**Comment by ljbade** [comment]
all thats really needed is another variable I would think that is set to the location of the branch.

perhaps just add a `MASON_BRANCH = pwd` to the top of each `script.sh`

**Comment by kkaefer** [comment]
This is by design: When installing a library with mason, we're not checking out the whole repository. Instead, we're just downloading the `script.sh` file: https://github.com/mapbox/mason/blob/861ddecd3e78ee89e2ee681509aec312810374a9/mason#L61-L65

If you need additional files, you have to download them manually in your install script.

**Comment by ljbade** [comment]
@kkaefer I think @springmeyer is cooking something up in the `mason link` PR

**Comment by springmeyer** [comment]
> If you need additional files, you have to download them manually in your install script.

This is what I've started doing for patch files (https://github.com/mapbox/mason/blob/gdal-1.11.1/script.sh#L32). It is a bit odd in that you need to commit the files before you can use them (making testing locally or offline impossible) but I think it should work for now.

> @kkaefer I think @springmeyer is cooking something up in the mason link PR c67cda5

@ljbade - that is unrelated to this.

> perhaps just add a MASON_BRANCH = pwd to the top of each script.sh

Yeah that might be useful.

**Comment by ljbade** [comment]
hmm @springmeyer what about for libboringssl where i need to pull down a large number of different files?

**Comment by ljbade** [comment]
We now pull files directly.
