### ISSUE TITLE
Mason for `webp` on iOS does not download nor build

### ISSUE THREAD

**Issue by roblabs** [mapbox/mason#450]
Attempting to include `webp` in an iOS project via Mason.  There is no prebuilt package for iOS, so it attempts to build then fails at a step called `lipo`.

* I understand that iOS is not supported with a download package, 
* Any ideas why `lipo` fails?  _cf._ #400 

## Using these steps to reproduce

``` bash
mkdir ./mason
curl -sSfL https://github.com/mapbox/mason/archive/v0.13.0.tar.gz | tar --gunzip --extract --strip-components=1 --exclude="*md" --exclude="test*" --directory=./mason

export MASON_PLATFORM=ios
./mason/mason build webp 0.6.0
```

I have Xcode Version 8.3.3 (8E3004b) installed 

```
> clang -v
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

## Attempts to download, but not available
```
* Downloading binary package ios-8.0/webp/0.6.0.tar.gz...
* Binary not available yet for https://mason-binaries.s3.amazonaws.com/ios-8.0/webp/0.6.0.tar.gz
* Building for Platform 'ios/8.0'...

```

## Builds several flavors, but then fails at lipo 
```
input file lib-ios-arm64/libwebp.a is not a fat file
Non-fat file: lib-ios-arm64/libwebp.a is architecture: i386
* Creating Universal Binary...
fatal error: 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: 
lib-isim-i386/libwebp.a and lib-isim-x86_64/libwebp.a have the same architectures (i386) 
and can't be in the same fat output file
```

![webp](https://user-images.githubusercontent.com/118112/28351689-401efdf2-6c06-11e7-8be9-f743057f6c11.png)

**Comment by roblabs** [comment]
Until I can figure out mason for `webp`, I sorted out a solution for iOS using `WebP.framework`, https://github.com/roblabs/mapbox-gl-native#mapbox-gl--webp-for-ios

**Comment by romanroibu** [comment]
I have the same failure when trying to build `jpeg_turbo` for iOS. The `lipo` step is attempting to create a universal (multi-architecture) library from libraries built for different architectures (`armv7` and `arm64` for devices running iOS and `i386` and `x86_64` for the iOS simulator).

What I understand the problem to be: the libraries were supposed to be compiled for different architectures, but in reality are being compiled for the same one (`i386`). Inspecting the libraries with `lipo -info` confirms that this is in fact the case (all 4 report the architecture being `i386`).

Unfortunately, I wasn't able to find the root of the problem beyond that.

**Comment by roblabs** [comment]
In the `webp` case it is failing at `lipo` for the simulator.   

``` bash
lib-isim-i386/libwebp.a and lib-isim-x86_64/libwebp.a have the same architectures (i386) 
```

Is there anyway to run `lipo` manually or ensure that the compilation is not done for `i386` across all architectures?

**Comment by romanroibu** [comment]
`lipo` just combines the compiled libraries into one. The problem is somewhere in the compilation process (before `lipo`), but I wasn't able to track it.

**Comment by kkaefer** [comment]
Fixed in #465.

```
./mason install webp 0.6.0
* Downloading binary package ios-8.0/webp/0.6.0.tar.gz...
* Installed binary package at /Users/kkaefer/Code/mason/mason_packages/ios-8.0/webp/0.6.0
```

**Comment by roblabs** [comment]
I've tested that `mason install webp 0.6.0` works.   Thanks @kkaefer 

I have not been successful with `mason build webp 0.6.0`  (Same error with `lipo`)

But for now, `mason install` is good enough.

**Comment by kkaefer** [comment]
@roblabs did you upgrade the mason repository to include the commit mentioned in #465?

**Comment by roblabs** [comment]
My apologies, it works after `git pull` on the mason repo.  I recommend closing #450.  

I had (wrongly) assumed that the `make clean` was related to the package on the server.  I [see now](https://github.com/mapbox/mason/pull/465/files) it was the `mason/scripts/webp` folder.

## Test

```bash
cd mason
git pull
```

### Successful build for macOS, folder is `osx-x86_64`
``` bash
./mason build webp 0.6.0
```

### Successful build for macOS, folder is `ios`
```bash
export MASON_PLATFORM=ios
./mason build webp 0.6.0
```

**Comment by roblabs** [comment]
### Update on testing 

When including WebP via Mason for building in a mapbox-gl build, the tar ball for the Mason WebP for iOS is missing an .ini file.

#### Error
---

```
CMake Error at cmake/mason.cmake:120 (message):
  [Mason] Could not find mason.ini for package webp 0.6.0
```

#### Likely place to fix this

* This tar ball does not contain the mason.ini file, `mason_packages/.binaries/ios-8.0/webp/0.6.0.tar.gz`

* But this tar ball does contain mason.ini, `mason_packages/.binaries/osx-x86_64/webp/0.6.0.tar.gz`


#### Work around 

As a work around, I created `mapbox-gl-native/mason_packages/ios-8.0/webp/0.6.0/mason.ini` with these contents.

```
name=webp
version=0.6.0
platform=ios
platform_version=8.0
include_dirs={prefix}/include
static_libs={prefix}/lib/libwebp.a

```
