### ISSUE TITLE
Boost 1.64.0

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mason#464]
Boost 1.64 got released in April: http://www.boost.org/users/history/version_1_64_0.html
Looks like CMake 3.8.2 (in Mason) already has support for it: https://github.com/Kitware/CMake/commit/6bd28fd235f75d150b1a4849c5b134f5e2766764

---

There's also an upcoming 1.65 release, should roll out in the next weeks:
- http://www.boost.org/users/history/version_1_65_0.html
- https://lists.boost.org/boost-users/2017/08/87791.php

**Comment by springmeyer** [comment]
1.64.0 landed in #409 and 1.65.1 will land in #472. Both will be built against libstdc++-4.8-dev and as such should resolve the linking issues in https://github.com/Project-OSRM/osrm-backend/issues/3978.

**Comment by springmeyer** [comment]
#472 is now done.
