### ISSUE TITLE
Single Linux binary

### ISSUE THREAD

**Issue by ljbade** [mapbox/mason#47]
Related to https://github.com/mapbox/mason/issues/38

@mikemorris was running into problems where he was building everything from source since the only binaries Travis publish are for Ubuntu 12.04

Since Linux binaries are backwards compatible it makes sense to just switch to a single binary for all Linux x64 distros.

If we get feedback that some binary does not work on another distro like Fedora or such (although it should just work OK) we can revisit this.

**Comment by ljbade** [comment]
I made a PR here: https://github.com/mapbox/mason/pull/48

**Comment by springmeyer** [comment]
Looks like versioning ended up `linux-linux-{arch}`. Not a breaking problem, but odd looking.

**Comment by ljbade** [comment]
Oh will look into it next week

**Comment by ljbade** [comment]
I fixed the versioning.
