### ISSUE TITLE
mason fails when `lscpu` doesn't function

### ISSUE THREAD

**Issue by danpat** [mapbox/mason#482]
In an AWS Lambda environment, the use of `lscpu` gives this error message:

`lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory`

Because the `mason.sh` script has `set -e`, this causes it to abort.  I came across this trying to use `mason prefix` to find the path to a pre-installed binary (`mason` was used to *build* an image, which was then deployed to AWS Lambda, but `mason prefix` fails inside the Lambda environment).

Failure of `lscpu` probably shouldn't be shouldn't be fatal, or there should be a way to inject a value externally, and avoid the use of autodetection (i.e. if `MASON_CONCURRENCY` is already set, don't try to detect it).

**Comment by lightmare** [comment]
I guess this was fixed, eventually, in https://github.com/mapbox/mason/commit/e869d8430c4fd9a652b7ddb0ec6d7e44be0c610c
