### ISSUE TITLE
Build boringssl locally

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mason#50]
Need to rework the `boringssl` script a bit to conform to `mason` conventions better, be able to build locally and figure out why `libcrypto.a` ends up as a [malformed archive](https://github.com/mapbox/mapbox-gl-native/pull/754#issuecomment-70316916). Tracked down the original locations of dependencies currently on the [`boringssl-d3bcf13`](https://github.com/mapbox/mason/tree/boringssl-d3bcf13) branch:

- `deps/gyp` https://code.google.com/p/gyp/source/checkout
- `deps/gtest` https://code.google.com/p/googletest/source/checkout
- `gyp` https://src.chromium.org/viewvc/chrome/trunk/src/third_party/boringssl/

Is there an existing best practice for building gyp projects @springmeyer?

Currently tracking in https://github.com/mapbox/mason/tree/boringssl-d3bcf13-local/

**Comment by springmeyer** [comment]
I think I got it working https://travis-ci.org/mapbox/mason/builds/47323960

**Comment by ljbade** [comment]
Awesome, thanks for looking at this guys.

Next thing will be to get libcurl building locally so `make test` can be used to ensure HTTPs is working properly.

**Comment by ljbade** [comment]
Also you can switch back to the original boringssl repo now that we are using gyp.

**Comment by springmeyer** [comment]
both of those things are done @ljbade. can you test?

**Comment by ljbade** [comment]
@springmeyer I am still getting malformed archive errors with the latest single-linux build of boringssl.

**Comment by ljbade** [comment]
@springmeyer Look like travis is having the same problem:
https://travis-ci.org/mapbox/mason/jobs/47325412#L293-L297

**Comment by ljbade** [comment]
@springmeyer Can't see anything wrong in boringssl build:
https://travis-ci.org/mapbox/mason/jobs/47323962#L441-L443

Only thing I can think of is that Chrome's `gyp` builds everything into a single `libboringssl.a` whereas `libcurl` expects the OpenSSL layout of separate `libssl.a` and `libcrypto.a` (which what boringssl'c CMake builds). So I just copy `libboringssl.a` to `libssl.a` and `libcrypto.a` in the `boringssl` `script.sh`.

Could this be the problem?

**Comment by springmeyer** [comment]
@ljbade I think the issue is that gyp by default builds a "thin" static library. This means that the .a holds references to object files rather than the objects themselves which is a handy optimization when building locally. But of course this breaks in our case because we are only tarring up the .a file and not the object files. So the solution is to ask for a normal archive, or what gyp calls a "Standalone" static library. I've done this in https://github.com/mapbox/mason/commit/87b793c5ddde5ba2f0d1733fca4e8676ee584fbe. Can you give that a shot?

**Comment by mikemorris** [comment]
Testing this today I'm hitting linker errors on Linux again:
```
  flock ../Release/linker.lock g++ -Wl,--start-group /home/mikemorris/mapbox-gl-native/build/libmbgl.a -lz -lm -L/home/mikemorris/mapbox-gl-native/mason_packages/linux-linux-x86_64/jpeg/v8d/lib -ljpeg -lpthread -ldl -lrt -L/home/mikemorris/mapbox-gl-native/mason_packages/linux-linux-x86_64/libcurl/7.38.0-boringssl/lib -lcurl -lssl -lcrypto -lz -ldl -L/home/mikemorris/mapbox-gl-native/mason_packages/linux-linux-x86_64/nunicode/1.5.1/lib -lnu  -o ../Release/mapbox-gl ../Release/obj.target/linuxapp/linux/main.o ../Release/obj.target/linuxapp/platform/default/settings_json.o ../Release/obj.target/linuxapp/platform/default/glfw_view.o ../Release/obj.target/linuxapp/platform/default/log_stderr.o ../Release/obj.target/libmbgl-linux.a ../Release/obj.target/libmbgl-core.a -Wl,--end-group -lz -lm /home/mikemorris/mapbox-gl-native/mason_packages/linux-linux-x86_64/sqlite/3.8.6/lib/libsqlite3.a -ldl -lpthread /home/mikemorris/mapbox-gl-native/mason_packages/linux-linux-x86_64/glfw/e1ae9af5/lib/libglfw3.a -lrt -lXrandr -lXinerama -lXi -lXcursor -lGL -lm -ldl -lXrender -ldrm -lXdamage -lX11-xcb -lxcb-glx -lxcb-dri2 -lxcb-dri3 -lxcb-present -lxcb-sync -lxshmfence -lXxf86vm -lXfixes -lXext -lX11 -lpthread -lxcb -lXau -lXdmcp /home/mikemorris/mapbox-gl-native/mason_packages/linux-linux-x86_64/libcurl/7.38.0-boringssl/lib/libcurl.a -L/home/mikemorris/mapbox-gl-native/mason_packages/linux-linux-x86_64/libcurl/7.38.0-boringssl/lib -lcurl -lssl -lcrypto -lz -ldl -lz /home/mikemorris/mapbox-gl-native/mason_packages/linux-linux-x86_64/libpng/1.6.13/lib/libpng.a
/home/mikemorris/mapbox-gl-native/build/libmbgl.a(libcurl_la-openssl.o): In function `x509_name_oneline':
openssl.c:(.text+0x2ed): undefined reference to `BIO_get_mem_ptr'
/home/mikemorris/mapbox-gl-native/build/libmbgl.a(libcurl_la-openssl.o): In function `X509V3_ext':
openssl.c:(.text+0x861): undefined reference to `BIO_get_mem_ptr'
/home/mikemorris/mapbox-gl-native/build/libmbgl.a(libcurl_la-openssl.o): In function `servercert':
openssl.c:(.text+0x17ac): undefined reference to `BIO_get_mem_ptr'
openssl.c:(.text+0x18d6): undefined reference to `BN_num_bytes'
openssl.c:(.text+0x18f3): undefined reference to `BN_num_bytes'
openssl.c:(.text+0x1910): undefined reference to `BN_num_bytes'
openssl.c:(.text+0x192d): undefined reference to `BN_num_bytes'
openssl.c:(.text+0x194a): undefined reference to `BN_num_bytes'
/home/mikemorris/mapbox-gl-native/build/libmbgl.a(libcurl_la-openssl.o):openssl.c:(.text+0x1967): more undefined references to `BN_num_bytes' follow
/home/mikemorris/mapbox-gl-native/build/libmbgl.a(libcurl_la-openssl.o): In function `Curl_ossl_init':
openssl.c:(.text+0x3163): undefined reference to `OpenSSL_add_all_algorithms'
collect2: error: ld returned 1 exit status
make[1]: *** [../Release/mapbox-gl] Error 1
make[1]: Leaving directory `/home/mikemorris/mapbox-gl-native/build/linux'
make: *** [linux] Error 2
```
However, it looks like `libcurl` is successfully being built with `https` support now:
```
mikemorris@ubuntu:~/mapbox-gl-native$ ./mason_packages/linux-linux-x86_64/libcurl/7.38.0-boringssl/bin/curl -V
curl 7.38.0 (x86_64-unknown-linux-gnu) libcurl/7.38.0 BoringSSL/0.0.0 zlib/1.2.8
Protocols: http https
Features: IPv6 Largefile SSL libz
```

**Comment by ljbade** [comment]
Argh, will look into this later.

**Comment by ljbade** [comment]
@springmeyer OK that got libcurl building locally

**Comment by ljbade** [comment]
OK so libcurl with openssl passes 78% of tests, with boringssl also passes 78%. So not sure what is needed for 100%.

**Comment by ljbade** [comment]
Looks like I am getting similar link errors:

```
/home/leith/mb/mbgl-linux/build/libmbgl.a(libcurl_la-openssl.o): In function `x509_name_oneline':
openssl.c:(.text+0x5e): undefined reference to `BIO_get_mem_ptr'
/home/leith/mb/mbgl-linux/build/libmbgl.a(libcurl_la-openssl.o): In function `X509V3_ext':
openssl.c:(.text+0x339): undefined reference to `BIO_get_mem_ptr'
/home/leith/mb/mbgl-linux/build/libmbgl.a(libcurl_la-openssl.o): In function `servercert':
openssl.c:(.text+0x1866): undefined reference to `BIO_get_mem_ptr'
openssl.c:(.text+0x1995): undefined reference to `BN_num_bytes'
openssl.c:(.text+0x19b7): undefined reference to `BN_num_bytes'
openssl.c:(.text+0x19d9): undefined reference to `BN_num_bytes'
openssl.c:(.text+0x19fb): undefined reference to `BN_num_bytes'
openssl.c:(.text+0x1a1d): undefined reference to `BN_num_bytes'
/home/leith/mb/mbgl-linux/build/libmbgl.a(libcurl_la-openssl.o):openssl.c:(.text+0x1a3f): more undefined references to `BN_num_bytes' follow
/home/leith/mb/mbgl-linux/build/libmbgl.a(libcurl_la-openssl.o): In function `Curl_ossl_init':
openssl.c:(.text+0x3275): undefined reference to `OpenSSL_add_all_algorithms'
collect2: error: ld returned 1 exit status
``` 

Going to have to hunt around in openssl.c from libcurl to see where these are used and if BoringSSL provides them.

**Comment by ljbade** [comment]
Looking at BoringSSL's headers those functions are defined. Next step is to figure out why they are not in the lib.

**Comment by ljbade** [comment]
`OpenSSL_add_all_algorithms` is an empty function so safe to remove.

`BN_num_bytes` is in `crypto/bn/bn.c` and is used all over the place in BoringSSL so not sure why it isn't finding it.

`BIO_get_mem_ptr` is in `crypto/bio/bio_mem.c` and is not referenced elsewhere in BoringSSL.

Now to figure out why these exported functions are missing.

**Comment by ljbade** [comment]
@springmeyer Do you think my libcrypto/libssl copy is causing the problem?

**Comment by springmeyer** [comment]
@ljbade Took a look just now. I think the problem is that the `libcurl-7.38.0-boringssl` install was putting `-lcrypto` and `-lssl` in the linking flags but boringssl was not actually being installed. So the system `libcrypto` and `libssl` were being found and used. To make sure this does not happen again I've pushed changes to the mason packages and the mbgl branch to explicitly link to `libboringssl.a`.

**Comment by mikemorris** [comment]
So testing this is interesting... no more linker errors, `libcurl` looks to be built successfully with `https` support and `make run-linux` is working on OS X, but `make run-linux` just yields a blank X11 window on my Linux VM. Looks like there's still a linker error on `make test` too, but that should be a simple fix I'm guessing.

**Comment by mikemorris** [comment]
Oh, and I have no idea if this is related, but I am seeing this solitary error:
```
[ERROR] OpenGL: GLFW error (65544): X11: RandR gamma ramp support seems broken
```

**Comment by mikemorris** [comment]
Oh WTF, turned on `BUILDTYPE=Debug` and the problem is tile requests with a revoked token attached, exactly like what I saw with that hidden SQLite cache on OS X before.

**Comment by mikemorris** [comment]
Access token issue fixed by https://github.com/mapbox/mapbox-gl-native/pull/768, closing this as `mason` now successfully builds `boringssl` locally.
