### ISSUE TITLE
Build libcurl-7.38.0-boringssl locally

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mason#52]
Currently fails with:
```
mason_packages/.scripts/libcurl-7.38.0-boringssl.sh: line 33: openssl.patch: No such file or directory
```

**Comment by ljbade** [comment]
It sees to run OK here? OSX?

**Comment by mikemorris** [comment]
OS X and Linux. Resolved if you manually `wget https://raw.githubusercontent.com/mapbox/mason/libcurl-7.38.0-boringssl/openssl.patch`, but this should happen automatically.
