### ISSUE TITLE
Package llvm 5.0.1

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#523]
llvm 5.0.1 is due to be released Dec 1 (https://lists.llvm.org/pipermail/llvm-dev/2017-September/117729.html).

It will show up at http://releases.llvm.org/ when ready.

Downstream users of mason will want to upgrade when 5.0.1 is available in mason, in particular to take advantage of the latest clang-tidy checks and sanitizers.

In https://github.com/mapbox/mason/pull/452, we gained docs for how to build llvm for both Mac OSX and Linux on a Mac, locally. This is needed since llvm takes way too long to compile for the build to be viable on travis.

So for the near term we will keep packaging locally on a Mac. I've spoke with @GretaCB about pairing with me on the 5.0.1 release package to spread knowledge on this process.

In the long term an approach that builds the linux version (at least) in an automated way on AWS would be ideal (perhaps using https://github.com/mapbox/stork/aws codebuild). As far as OS X, we could try out the new OS X support on circleCI 2.0: maybe it would be fast enough to finish/maybe note. Beyond that the only other idea for better automation for OS X would be trying out cross-compiling with https://github.com/tpoechtrager/osxcross.

/cc @daniel-j-h @tmpsantos @brunoabinader @karenzshea

**Comment by springmeyer** [comment]
LLVM 5.0.1 is out: https://lists.llvm.org/pipermail/llvm-announce/2017-December/000076.html /cc @GretaCB - let's plan to pair on this in early 2018.

**Comment by TheMarex** [comment]
Since I'm bumping the clang version for OSRM 5.16 to clang 5.0, do you think we can expect `5.0.1` to land in the next few weeks?

**Comment by springmeyer** [comment]
Done in #547 - nice work @GretaCB && @karenzshea!!
