### ISSUE TITLE
Always set -std=c++11

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#54]
We should only support >= c++11 for compiling C++ packages. So this is a ticket reminder for adding `-std=c++11` soon for linux in the same was as we added `-fPIC` https://github.com/mapbox/mason/commit/2a955a1650fe65bf31e5a198972244541693e897.

**Comment by ljbade** [comment]
The should only be in CPPFLAGS not CFLAGS

**Comment by ljbade** [comment]
Done.

**Comment by springmeyer** [comment]
Thanks for moving on this. Because precise does not ship with a capable C++11 compiler we need to upgrade the toolchain so that `-std=c++11` actually works. Getting this working in a sudoless fashion is a work in progress. I'll re-open this ticket until I can confirm it is working.

**Comment by springmeyer** [comment]
https://github.com/mapbox/mason/blob/master/scripts/setup_cpp11_toolchain.sh is working and able to upgrade to a c++11 viable toolchain. Using clang-3.5 because why not use the latest and greatest (and this is proven to work for portable binaries in mapnik-packaging). Next steps are:

 - [ ] get all boost libs building in c++11 mode (will fail until they do)
 - [ ] icu
 - [ ] harfbuzz
 - [ ] nunicode?
 - [ ] gdal
