### ISSUE TITLE
GDAL not compiled with GEOS

### ISSUE THREAD

**Issue by mattficke** [mapbox/mason#553]
When trying to use the [`-wrapdateline`](http://www.gdal.org/ogr2ogr.html) option with Mason's ogr2ogr ([v2.2.3](https://github.com/mapbox/mason/blob/master/scripts/ogr2ogr/2.2.3/script.sh)), the following error is thrown:

```
ERROR 6: GEOS support not enabled.
```

Poking around, it looks like this is because GDAL is compiled with the [`--with-geos=no`](https://github.com/mapbox/mason/blob/master/scripts/gdal/2.2.3/script.sh#L138) flag.

Would it be possible to add a version of GDAL/OGR with GEOS enabled?

cc @mapbox/core-tech @mapbox/geocoding-gang

**Comment by springmeyer** [comment]
Thanks for ticketing. The motivation in leaving out GEOS support was two fold:

 - until it was needed I figured it would be ideal to leave out (smaller binary size and less hassle to ensure the same geos version is used in gdal and the postgis version that gdal is linked to)
 - build variants (custom build configurations for pre-compiled packages) are something I'd like to add proper support for in future mason v2. So, we'd have a nice way, given a single package script to generate named variants with/without certain features.

But, yes, this would be totally reasonable/easy to add now. In fact that feature feels pretty critical to `ogr2ogr` usage and I can imagine needing it for https://github.com/mapbox/preprocessorcerer in the near future.

**Comment by springmeyer** [comment]
work on this at https://github.com/mapbox/mason/pull/554

**Comment by springmeyer** [comment]
@mattficke #554 is merged and packages are published. Can you test with:

```bash
git clone https://github.com/mapbox/mason.git
./mason/mason install gdal 2.2.3-1
```

**Comment by mattficke** [comment]
@springmeyer installs successfully on both osx and linux.

**Comment by springmeyer** [comment]
Great @mattficke - please close this issue once you've confirmed that the flag works.

**Comment by mattficke** [comment]
@springmeyer confirmed that the flag works if I hack the install script so that ogr2ogr@2.2.3 uses gdal@2.2.3-1. Is the next step to add a corresponding ogr2ogr script that sets `MASON_VERSION` to 2.2.3-1? I can open a PR if so.

**Comment by springmeyer** [comment]
Yes that is a great next step. Please go ahead and add that package and let me know if you need a review.

**Comment by mattficke** [comment]
Done in #555
