### ISSUE TITLE
Android ports needing work

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#56]
High level ticket to track apps that don't work yet on android but likely could/should if needed.

### libjpeg-turbo

Currently stuck on what looks like an outdated config.sub/config.guess:

```
checking build system type... x86_64-unknown-linux-gnu
checking host system type... Invalid configuration `arm-linux-androideabi': system `androideabi' not recognized
configure: error: /bin/bash ./config.sub arm-linux-androideabi failed
```

https://travis-ci.org/mapbox/mason/jobs/48413479#L155

### webp

Can't remember the error - would need to re-enable travis android builds to take a look.

**Comment by ljbade** [comment]
Soon I will start working on expanding the Android ABIs we compile for

**Comment by ljbade** [comment]
I have started adding the extra ABIs.

So far I discovered that arm64 support is recent:
- libpng needs to be >= 1.6.15
- jpeg does not recognise arm64 in v8d

**Comment by ljbade** [comment]
Also a number of `.travis.yml` files still use NDK r10c for some reason, I am updating these as I find them.

**Comment by ljbade** [comment]
- openssl does not have 64-bit Android config variants, but I wonder if linux variants work just as well

**Comment by jfirebaugh** [comment]
Stale.
