### ISSUE TITLE
Package LLVM 6.0.0

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#573]
Hot on the heals of LLVM 5.0.1 (#523) the LLVM 6.0.0 release is out:

 - https://lists.llvm.org/pipermail/llvm-announce/2018-March/000077.html
 - http://releases.llvm.org/6.0.0/docs/ReleaseNotes.html

Observant readers will notice that a v6.0.0 package already exists in mason. This is because I have a habit of testing release before they are official. Once official we build a final package and replace the existing one, auto-upgrading anyone using it downstream.

So, for this release we'll likely need to clear out the `6.0.0` directories first, before running the `./utils/llvm.sh create ...` script described at https://github.com/mapbox/mason/tree/master/scripts/llvm/base#step-4-create-the-new-package

TODO as part of this release:

 - https://github.com/mapbox/mason/issues/563

**Comment by allieoop** [comment]
Packaged and published LLVM 6.0.0: https://github.com/mapbox/mason/commit/fe42dab8309ba0d7bfa7c3a107553da93e76bda1
