### ISSUE TITLE
Culling packages

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#60]
Packages that can be deleted:
- [x] nunicode != latest version (1.5.1)
- [x] libpng != latest version

**Comment by ljbade** [comment]
Oh yeah remove the old packages now that I merged updates into mapbox-gl-native.

Are mason packages referenced from anywhere else?

**Comment by ljbade** [comment]
More for culling:
- [ ] glfw
- [ ] jpeg
- [ ] libcurl - need to test 7.40 with boringssl now that I the patch should be in there - or is it coming in 7.41?
- [ ] libuv (once the iOS lipo bug is fixed)
- [ ] mesa
- [ ] openssl
- [ ] sqlite

**Comment by springmeyer** [comment]
:+1: 

> Are mason packages referenced from anywhere else?

only mbgl and mapnik - let's me ruthless in this early stage in cleaning up packages. If things break downstream they likely should be breaking (so we fix).

**Comment by yhahn** [comment]
... 0 tags? ; ) https://github.com/mapbox/mason/tags

**Comment by ljbade** [comment]
@springmeyer which GLFW is the latest one?

**Comment by springmeyer** [comment]
@ljbade @kkaefer would know

**Comment by springmeyer** [comment]
@yhahn packages themselves are the "releases" and so I'd not been planning on mason tags (like homebrew https://github.com/Homebrew/homebrew/releases)

**Comment by ljbade** [comment]
I prefer the branch system as it allows updates to an existing version, such as extending the Android ABIs I did recently.

**Comment by kkaefer** [comment]
@yhahn I thought about using tags, but that means we'd have two version numbers per package, the packaged software's version and the package version, which is probably going to be confusing; the idea is that a package of a software version doesn't need to be versioned; only bufixed, i.e. there should not be any need for a consumer to pin to an "old" package release.

**Comment by kkaefer** [comment]
We can switch to GLFW 3.1, which was released in a few weeks ago and has all the bug fixes we need.

**Comment by mikemorris** [comment]
With https://github.com/mapbox/mapbox-gl-native/pull/796, `mesa` packages prior to `10.4.3` should be clear to be culled.

**Comment by mikemorris** [comment]
From @jfirebaugh:
> did someone delete mason branches that are in use? specifically mesa-10.3.1?
old branches / pull requests are now failing
"old" as in "created 3 days ago"
let's be a little more conservative in deleting mason branches

**Comment by jfirebaugh** [comment]
I've restored the mesa-10.3.5 branch so that mapbox-gl-js can build successfully again and ticketed an update: https://github.com/mapbox/mapbox-gl-js/issues/975.

> let's be ruthless in this early stage in cleaning up packages. If things break downstream they likely should be breaking

A little less ruthless please -- let's update downstream projects _before_ removing old branches and binaries in mason. Breaking unexpectedly means context switches and time spent tracking down the failures without having all the context.

**Comment by ljbade** [comment]
@jfirebaugh perhaps a way to mark branches as "retired" so that they should not be referenced from master rather, to make sure people upgrade before they merge

@springmeyer a way to automatically detect whether packages are still referenced in branches or on peoples computers may be needed, since it is impossible to know if someone has old mason sitting on their computer still

perhaps a way to archive deleted branches - @springmeyer perhaps store build scripts on s3 rather than mason branch? then old scripts can just stay there after the branch is deleted

**Comment by springmeyer** [comment]
> let's update downstream projects before removing old branches

Absolutely. Sorry that happened - not my intention. Also +1 for @mikemorris being point for mesa across all repos that use it as it is surely a complex dep.

As far as how to prevent breakages in the future (even when we are careful) I've been thinking that mason "knowing" what apps depend on what packages is way out of scope - we don't want to spend time building that. Instead we could consider other cheaper ideas like adding a `mason freeze` command that would tar up a set of packages and archive those on S3 in a spot that does not ever get culled. In times of fast dev with mbgl-native where much of the work is around managing deps and testing new versions, we'd continue to use mason as we do currently. But ideally this usage becomes a minority over time and using a single "frozen" tarball of deps would be stable, fast, and not a major pain to update occasionally.

**Comment by springmeyer** [comment]
> @springmeyer a way to automatically detect whether packages are still referenced in branches or on peoples computers may be needed, since it is impossible to know if someone has old mason sitting on their computer still

@ljbade your comment came in just after I posted above that I think this is out of scope. Though surely it would be useful.

> perhaps a way to archive deleted branches - @springmeyer perhaps store build scripts on s3 rather than mason branch? then old scripts can just stay there after the branch is deleted

Will mull on this. I'd rather have the thing that gets solidly archived be what apps really depend on (the deps in a logical local directory) and not mason itself.

**Comment by ljbade** [comment]
@springmeyer your "freeze" idea would work as well. Basically a way to disconnect branch deletion from breaking references to old versions.

Also agree reverse dependency is hard and likely not work it if "freeze" works.

I still like the idea that when a branch is deleted that version is "retired" and should spit out a nice big red warning to the screen that the developer should update their branch before merging.

**Comment by ljbade** [comment]
@springmeyer should also spit out a big red warning when current .mason does not match master, might help people like @mikemorris

**Comment by springmeyer** [comment]
Now at https://github.com/mapbox/mason/issues/67#issuecomment-221112427
