### ISSUE TITLE
Publish a release

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mason#663]
The latest release is from February https://github.com/mapbox/mason/releases

By now we updated multiple scripts and fixed various bugs. It would be great to get another release out.

**Comment by springmeyer** [comment]
Most downstream clients are now either mason.cmake or https://github.com/mapbox/mason-js. Both pull directly from s3 and don't need a release, so we've stopped making regular releases. 

If you need a release you could run one how by following https://github.com/mapbox/mason/blob/master/contributing.md.

**Comment by daniel-j-h** [comment]
I see. If we no longer do releases should we mention that in the readme and update the installation instruction to not point to an outdated release but maybe master instead?

**Comment by springmeyer** [comment]
Releases are still worthwhile, just not something anyone, that I'm aware of, have bandwidth for. Anyone can do one however per https://github.com/mapbox/mason/blob/master/contributing.md.
