### ISSUE TITLE
Drop pkg-config for static libs

### ISSUE THREAD

**Issue by ljbade** [mapbox/mason#68]
For all the statically linked libs we should stop using `pkg-config` becuase most libraries do not provide a valid `.pc` file for static linking.

See http://stackoverflow.com/questions/27586503/how-to-use-pkg-config-to-link-a-library-statically

Currently I am seeing link commnads with a mix of static and dynamic link flags for the same library. This is just asking for trouble, no to mention a missing symbol will result in a run-time error instead of a compile time error - I have hit this many times on Android.

@kkaefer Said `pkg-config` is needed for GLFW, so assuming they maintain a valid `.pc` we can leave that lib alone.

**Comment by springmeyer** [comment]
I'm on board with reducing dependence on pkg-config wherever possible (#12). But GLFW is certainly a case we should keep pkg-config around for.

**Comment by kkaefer** [comment]
An example of a package that seems broken is curl and openssl:
```
'openssl_static_libs%': ['/Users/kkaefer/Code/gl/native/mason_packages/android-arm-v5-9/openssl/1.0.1l/lib/libssl.a'],
'openssl_cflags%': ['-I/Users/kkaefer/Code/gl/native/mason_packages/android-arm-v5-9/openssl/1.0.1l/include'],
'openssl_ldflags%': ['-L/Users/kkaefer/Code/gl/native/mason_packages/android-arm-v5-9/openssl/1.0.1l/lib', '-lssl', '-lcrypto', '-ldl'],
'curl_static_libs%': ['/Users/kkaefer/Code/gl/native/mason_packages/android-arm-v5-9/libcurl/7.40.0/lib/libcurl.a'],
'curl_cflags%': ['-DCURL_STATICLIB', '-I/Users/kkaefer/Code/gl/native/mason_packages/android-arm-v5-9/libcurl/7.40.0/include'],
'curl_ldflags%': ['-L/Users/kkaefer/Code/gl/native/mason_packages/android-arm-v5-9/libcurl/7.40.0/lib', '-lcurl', '-lssl', '-lcrypto', '-lssl', '-lcrypto', '-lz'],
```

You'll see that the `ldflags` contain other libs as well, even though they should be folded into the static archives.

**Comment by springmeyer** [comment]
Closing. The motivation for this ticket was solved by using `mason.cmake` after https://github.com/mapbox/mapbox-gl-native/pull/5359

**Comment by kkaefer** [comment]
In particular, this is solved by including a `mason.ini` file in packages to avoid calling the original packages build system in https://github.com/mapbox/mason/pull/176
