### ISSUE TITLE
add script for GDAL 2.4

### ISSUE THREAD

**Issue by boblannon** [mapbox/mason#681]
I may be able to submit a PR for this, but if anyone has bandwidth to do so before I get a chance, it'd be really awesome. The existing GDAL scripts look pretty involved wrt dependencies, and my inexperience with the libraries involved means I'll probably move pretty slowly.

Per [release notes](https://trac.osgeo.org/gdal/wiki/Release/2.4.0-News) GDAL 2.4.0 is particularly exciting because it adds the `GeoJSONSeq` driver, allowing direct conversion/output of newline (or record-separator) delimited GeoJSON. As this is a popular format for storage of large datasets, having the ability to work with it directly is a really huge quality of life improvement.

**Comment by springmeyer** [comment]
@boblannon would be great to do this. An updated version could also be used as a dependency in upcoming postgis versions (refs #678). I'm happy to pair with you to get this done. Let me know if you've started at all.

**Comment by springmeyer** [comment]
I ended up needing to package GDAL 2.4.1 as part of getting latest PostGIS working: https://github.com/mapbox/mason/pull/685. So this is done now and I've also added a small guide for how others can package a new GDAL version in the future: https://github.com/mapbox/mason/blob/006d471dc2253de523b10848ed6c179e11c8cb60/scripts/gdal/2.4.1/readme.md

**Comment by boblannon** [comment]
wooooow, so none of the other dependency versions needed to change? sheesh, i feel silly for not just trying.

**Comment by springmeyer** [comment]
> wooooow, so none of the other dependency versions needed to change?

Correct. It would be a really good idea to do a pass to update all the deps versions. But it was unneeded for a new gdal build.
