### ISSUE TITLE
zlib on windows

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mason#7]
Recording some findings:

  - zlib 1.2.8 + libtiff 4.x fails in [this test](https://github.com/mapnik/node-mapnik/blob/bbaf409d0d02addcc463ae9adbc706d5cb14539a/test/image.test.js#L274-L276) because it basically appears that tiffs that have zlib compression cannot be opened. The errors you see from libtiff are:

```
ZIPSetupDecode: (null)
```

First I tried upgrading to libtiff HEAD and building gdal against this external libtiff (thinking I had a version clash) and that changed the error to:

```
ZipSetupDecode: .
```

But the tiff still could not be opened. After reading http://www.asmail.be/msg0054830467.html I got the idea of downgrading to zlib 1.2.5 since that is what the libpng windows visual studio files use. I could not find zlib 1.2.5 at http://zlib.net/ but was able to download it from http://sourceforge.net/projects/libpng/files/zlib/1.2.5/. Now things work:

   - libtiff: https://github.com/vadz/libtiff/commit/bf3abf5e663252d231c5f01c20a20f8530047ca0
   - zlib 1.2.5
   - build scripts from libpng 1.6.10

**Comment by rouault** [comment]
@springmeyer Could you check that the libtiff issue was a conflict with the zlib bundled in node.js ? Is there anything holding off the libtiff release ?

**Comment by springmeyer** [comment]
> Could you check that the libtiff issue was a conflict with the zlib bundled in node.js ?

@BergWerkGIS has been looking into this and I think the verdict was that the libpng visual studio file may have been at fault, but I'll let him summarize.

> Is there anything holding off the libtiff release ?

No! All clear. Thanks for checking :)

**Comment by BergWerkGIS** [comment]
@rouault @springmeyer haven't see any failed tests in `mapnik` or `node-mapnik` tests sinced I dodged the `zlib` that was created by `libpng`and switched to our own `zlib 1.2.8` build:
https://github.com/BergWerkGIS/mapnik-dependencies/blob/windows/scripts/build_zlib.bat

**Comment by springmeyer** [comment]
Excellent, closing with the resolution being the switch to compiling zlib rather than using the libpng visual studio files and the cause still somewhat unknown.
