### ISSUE TITLE
Use a corporate proxy server

### ISSUE THREAD

**Issue by rbhatia46** [mapbox/mason#716]
Hi, I want to use a corporate proxy server for installing dependencies, any help around the same is appreciated.
Thanks

**Comment by danpat** [comment]
Mason uses `curl` to download things, so you can use all of `curl`'s proxy mechanisms.

The simplest way is to set the `HTTPS_PROXY` environment variable, see https://ec.haxx.se/usingcurl/usingcurl-proxies#proxy-environment-variables

**Comment by rbhatia46** [comment]
Thanks, configuring the proxy for cURL works for me
