### ISSUE TITLE
osmium-tool debug

### ISSUE THREAD

**Issue by rclark** [mapbox/mason#72]
@springmeyer I made [a branch for `osmium-tool-1.0.0`](https://github.com/mapbox/mason/blob/osmium-tool-1.0.0/script.sh) that [works on OSX](https://travis-ci.org/mapbox/mason/jobs/55750193) but [fails on linux](https://travis-ci.org/mapbox/mason/jobs/55750194#L254).

Looks like some issue with boost-program-options? I'm hoping that you'll see what I'm doing wrong right away...

**Comment by rclark** [comment]
Fixed via https://github.com/mapbox/mason/commit/75ec92c2b95dcbd5c95305b180db339c7f6b2502

**Comment by springmeyer** [comment]
Yes, that is needed for C++ apps. nice work!

**Comment by springmeyer** [comment]
BTW, incase you looked inside that script: what it is doing is installing a clang/llvm based c++ toolchain in a sudoless way. Its a quick hack and something I plan to replace with actual mason packages of the latest and greatest c++ toolchain. Currently testing this over at https://github.com/springmeyer/build-llvm.
