### ISSUE TITLE
stxxl_shared not publishing correctly

### ISSUE THREAD

**Issue by danpat** [mapbox/mason#86]
Linking to `stxxl_shared` in bootstrap.sh still ends up fetching `stxxl/1.4.1.tar.gz` from S3, and `stxxl_shared/1.4.1.tar.gz` doesn't exist in the bucket.

It looks like MASON_NAME needs to be changed in `script.sh`

**Comment by springmeyer** [comment]
gah, sorry. Thanks for catching. Should be fixed once travis builds 1d91a48

**Comment by springmeyer** [comment]
sec, still broken.

**Comment by springmeyer** [comment]
should be fixed: https://travis-ci.org/mapbox/mason/builds/63430206
