### ISSUE TITLE
Upgrade to NDK r10e

### ISSUE THREAD

**Issue by ljbade** [mapbox/mason#87]
Tracking progress:
- [x] Create NDK branches and let Travis create tarballs
- [x] Update mason.sh to use new branches and check for any changes to NDK compile flags
- [ ] Rebuild Android mason packages
- [x] Update mapbox-gl-native to use new mason

**Comment by jfirebaugh** [comment]
For OSX Android development we're waiting on a [homebrew update](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/android-ndk.rb).

**Comment by jfirebaugh** [comment]
> Update mapbox-gl-native to use new mason

I tested this, without rebuilt Android mason packages, in https://github.com/mapbox/mapbox-gl-native/commit/e8379e62ba055a71c784402fdea14afbf656f787. The only issue was [this error](https://travis-ci.org/mapbox/mapbox-gl-native/jobs/63552720#L1031):

```
/usr/bin/ld.gold: fatal error: /home/travis/build/mapbox/mapbox-gl-native/mason_packages/linux-x86_64/android-ndk/mips-9-r10e/bin/../lib/gcc/mipsel-linux-android/4.9/../../../../sysroot/usr/lib/../lib/crtbegin_so.o: unsupported ELF machine number 8
clang35++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Perhaps this will be fixed with rebuilt Android mason packages.

**Comment by ljbade** [comment]
Yeah I think I have seen that MIPS error before.

**Comment by jfirebaugh** [comment]
Submitted a [homebrew PR](https://github.com/Homebrew/homebrew/pull/39972).

**Comment by ljbade** [comment]
Hmm seeing build failures for the Android Travis jobs: https://travis-ci.org/mapbox/mason/jobs/63572292#L119
`/home/travis/.mason/mason.sh: line 195: mason: command not found`

Looking at https://github.com/mapbox/mason/blob/master/mason.sh#L195 it appears that Android packages now need a local copy of mason?

@kkaefer when you switched to bundling NDK on mason did you update the packages to use this NDK?

**Comment by ljbade** [comment]
List of packages to update:
- [ ] freetype-2.5.5
- [ ] sqlite-3.8.8.3
- [ ] libuv-1.4.0
- [ ] libcurl-7.40.0
- (more to come)

**Comment by ljbade** [comment]
I am making a note that I will also recompile everything for soft float as part of fixing https://github.com/mapbox/mapbox-gl-native/issues/1468

**Comment by ljbade** [comment]
@springmeyer I tried the `export PATH` change inhttps://github.com/mapbox/mason/commit/f5188b1a38e152c7d45768390f68da2e77189546  but it still can't find mason - https://travis-ci.org/mapbox/mason/jobs/64556764

**Comment by danpat** [comment]
@ljbade: `.travis.yml.` is `git clone`-ing mason into `~/.mason`, but `script.sh` is adding `$(pwd)/.mason` to the `PATH`.  Looks like `$(pwd)` != `~`.

**Comment by ljbade** [comment]
@danpat thanks! It worked https://travis-ci.org/mapbox/mason/builds/65002293

**Comment by ljbade** [comment]
Don't close until at least nunicode fixed

**Comment by springmeyer** [comment]
> Don't close until at least nunicode fixed

Yes, sorry okay to keep open until all packages are fixed: https://github.com/mapbox/mason/issues/87#issuecomment-104452860

**Comment by ljbade** [comment]
nunicode is now fixed.

Only leaves zlib-system which is a system package so there is nothing really to rebuild.

I'll close here and track zlib in #99

**Comment by ljbade** [comment]
Found an issue with libcurl-1.4.0 it did not build with OpenSSL enabled.

It finds the pkg-config OK then fails one of the configure checks.

I looked at a freshly downloaded Android ARM-v7 openssl 1.0.1i package and it does have the CRYTO_lock symbol in libcrypto.a which is the test it is failing on Travis.

**Comment by ljbade** [comment]
Problem is here https://travis-ci.org/mapbox/mason/jobs/65008331#L345

On the Linux Travis job that test passes.

**Comment by ljbade** [comment]
I found the problem OpenSSL package script.sh keeps a copy of compile flags from mason.sh that I needed to update to soft floating point.
