### ISSUE TITLE
Add a android command to rebuild.sh

### ISSUE THREAD

**Issue by ljbade** [mapbox/mason#90]
To reduce the number of packages that need to be rebuilt when the NDK is upgraded or compile flags changes, a way to target only packages that have Android Travis jobs would make it a lot faster than rebuilding all the packages.

**Comment by springmeyer** [comment]
I think we need mason v2 soon that rethinks some fundamentals. It should be easy to rebuild packages that need rebuilding and impossible to overwrite packages that have already been published and should be immutable. Currently it is the opposite: its hard to selectively rebuild packages and too easy to overwrite immutable ones. Until we rethink this, a short term solution I think is to completely remove the `rebuild.sh` and just manually update what needs updating. Or write a custom script?

**Comment by jfirebaugh** [comment]
Agreed @springmeyer; published packages should be immutable. To cover cases where an existing package needs to be rebuilt at the same upstream version, I think we will need to institute a revision suffix, e.g. `package-1.2.4-6`.

**Comment by ljbade** [comment]
Hmm yeah it seems mason isn't scaling with large numbers of packages particularly if you change something that then effects a lot of them.

**Comment by jfirebaugh** [comment]
Obsoleted by #133.
