### ISSUE TITLE
proj cannot find proj_def.dat

### ISSUE THREAD

**Issue by jburgess777** [mapbox/mason#93]
I build and installed mapnik-3.0.0-rc2 by following the recommended steps which use the mason_packages. Later I built and mod_tile using @springmeyer's branch. Looking at the strace output shows that the process is failing to find some of the proj data files:
```
open("/home/travis/build/mapbox/mason/mason_packages/linux-x86_64/proj/4.8.0/share/proj/proj_def.dat", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/home/travis/build/mapbox/mason/mason_packages/linux-x86_64/proj/4.8.0/share/proj/null", O_RDONLY) = -1 ENOENT (No such file or directory)
```
The files ended up in the location below instead:
```
jburgess@mapnik3:~/mod_tile-springmeyer$ ls /home/jburgess/mapnik-3.0.0-rc2/mason_packages/linux-x86_64/proj/4.8.0/share/proj/
alaska  epsg  esri.extra  GL27    IGNF  nad27  nad.lst      ntv1_can.dat  nzgd2kgrid0005.gsb  proj_def.dat  stgeorge  stpaul  WI  world
conus   esri  FL          hawaii  MD    nad83  ntf_r93.gsb  null          other.extra         prvi          stlrnc    TN      WO
```

**Comment by springmeyer** [comment]
Same issue as #94: basically this is expected and so currently PROJ_LIB needs to be customized to the local system as per https://github.com/mapbox/mason/issues/94#issuecomment-105028715
