### ISSUE TITLE
ICU cannot find data files "could not create BreakIterator: U_MISSING_RESOURCE_ERROR"

### ISSUE THREAD

**Issue by jburgess777** [mapbox/mason#94]
I built and installed mapnik-3.0.0-rc2 by following the recommended steps which use the mason_packages. Later I built and mod_tile using @springmeyer's branch. There are errors from ICU failing to load its data files:
```
Mapnik LOG> 2015-05-24 16:23:51:  could not create BreakIterator: U_MISSING_RESOURCE_ERROR
```
strace shows that it expects to find them from /home/travis/... but that isn't where my local mapnik-3.0.0-rc2 compile downloaded them:
```
stat("/home/travis/build/mapbox/mason/mason_packages/linux-x86_64/icu/54.1/share/icu/54.1/icudt54l/brkitr/en_GB.res", 0x7fe83a9b9d50) = -1 ENOENT (No such file or directory)
stat("/home/travis/build/mapbox/mason/mason_packages/linux-x86_64/icu/54.1/share/icu/54.1/icudt54l.dat", 0x7fe83a9b9c50) = -1 ENOENT (No such file or directory)
stat("/home/travis/build/mapbox/mason/mason_packages/linux-x86_64/icu/54.1/share/icu/54.1/icudt54l/brkitr/en.res", 0x7fe83a9b9d50) = -1 ENOENT (No such file or directory)
stat("/home/travis/build/mapbox/mason/mason_packages/linux-x86_64/icu/54.1/share/icu/54.1/icudt54l/brkitr/root.res", 0x7fe83a9b9d50) = -1 ENOENT (No such file or directory)
```

**Comment by jburgess777** [comment]
It looks like it is possible to workaround this by setting ICU_DATA appropriately before using Mapnik/mod_tile:
```
export ICU_DATA=/home/jburgess/mapnik-3.0.0-rc2/mason_packages/linux-x86_64/icu/54.1/share/icu/54.1
```
Alternatively calling  `u_setDataDirectory()` should do the same thing. It would nice if the mason_packaged version of ICU worked without needing any manual fixups.

**Comment by springmeyer** [comment]
> It would nice if the mason_packaged version of ICU worked without needing any manual fixups.

Agree, need to find a cleaner way here. Sorry I missed documenting. My current approach is to do `source mapnik-settings.env` before running a program like renderd that was built against a Mapnik using mason. The `mapnik-settings.env` gets generated at https://github.com/mapnik/mapnik/blob/master/bootstrap.sh#L137-L142.

**Comment by jburgess777** [comment]
Sourcing `mapnik-settings.env` fixed both ICU and PROJ problems.

**Comment by springmeyer** [comment]
> Sourcing mapnik-settings.env fixed both ICU and PROJ problems.

Great. So, I'll close this issue now. To recap: some mason-packaged libraries like proj4, gdal, and icu need environment settings set at runtime to work correctly when run from any old directory. This is expected and okay.
